### ISSUE TITLE
Occasional 500 on departures/nearest

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/atb-bff#17]
Some requests to `v1/departures/nearest` seem to return 500. Can't find any actual details in the logs other than APIError:

```
Error: Internal Server Error
    at new APIError (/app/dist/src/service/types.js:21:28)
    at Object.<anonymous> (/app/dist/src/service/impl/stops.js:272:67)
    at step (/app/dist/src/service/impl/stops.js:44:23)
    at Object.throw (/app/dist/src/service/impl/stops.js:25:53)
    at rejected (/app/dist/src/service/impl/stops.js:17:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It doesn't look like it is based on input. Can return 200 and 500 on the same URL.

Related errors: https://console.cloud.google.com/errors/COjo_tSG4ZXBnQE?time=P1D&project=atb-mobility-platform

**Comment by torfjor** [comment]
I think this is related to rate limiting from Entur. If the searched for point has enough stops surrounding it, I can reproduce this.

I'll look into it, and also why the error traces are swallowed.

**Comment by torfjor** [comment]
I have a problem reproducing this. I added some more logging to hopefully catch this issue when it surfaces again.

**Comment by mikaelbr** [comment]
Yeah, seems to be rate limit issue: https://console.cloud.google.com/errors/COjo_tSG4ZXBnQE?time=P1D&project=atb-mobility-platform

**Comment by torfjor** [comment]
I've enabled rate limiting in c8ea262934462d482e14a210bebdc2bb0f1a2787.

Some limited testing locally shows that the issue is gone.
