### ISSUE TITLE
Improve error handling/error messages

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/atb-bff#2]
api.entur.io is down which causes the BFF to give error:

```json
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred"
}
```

due to 

```
APIError: request to https://api.entur.io/journey-planner/v2/graphql failed, reason: getaddrinfo ENOTFOUND api.entur.io
    at new APIError (/app/dist/src/service/types.js:19:28)
    at Object.<anonymous> (/app/dist/src/service/impl/journey.js:77:67)
    at step (/app/dist/src/service/impl/journey.js:33:23)
    at Object.throw (/app/dist/src/service/impl/journey.js:14:53)
    at rejected (/app/dist/src/service/impl/journey.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by torfjor** [comment]
Should we return a 503 with a helpful message in case of ECONNRESET, ETIMEDOUT, etc. upstream?

**Comment by mikaelbr** [comment]
I think that might be a good solution. It helps us give more precise feedback to the user.
